apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-api
  template:
    metadata:
      labels:
        app: super-api
    spec:
      containers:
      - name: super-api
        image: ghcr.io/gbaeke/super:1.0.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
