apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns3

namePrefix: dev-

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

patchesStrategicMerge:
  - memory.yaml
  
patchesJson6902:
  - target:
      kind: Deployment
      name: super-api
      version: v1
      group: apps
    path: patch.yaml
