apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-load
spec:
  template:
    spec:
      containers:
      - name: go-template-load
        resources:
          limits:
            memory: "128Mi"