apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true # remove Kubernetes objects when removed from git
      selfHeal: true # perform sync when changes are made to the live cluster
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: course/overlays/prod
    repoURL: 'https://github.com/gbaeke/argo-demo.git'
    targetRevision: HEAD
  project: default
