apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: course/overlays/prod
    repoURL: 'https://github.com/gbaeke/argo-demo.git'
    targetRevision: HEAD
  project: default
