apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodesub
  labels:
    app: nodesub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodesub
  template:
    metadata:
      labels:
        app: nodesub
    spec:
      containers:
      - name: node
        # make sure you use your image here
        image: gbaeke/dapr-sub
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
