apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodesub
  labels:
    app: nodesub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodesub
  template:
    metadata:
      labels:
        app: nodesub
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodesub"
        dapr.io/app-port: "3000"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: node
        image: gbaeke/dapr-sub
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
