apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap1
data:
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" }}
  {{ . }}: |-
    {{- $files.Get . | nindent 4 }}
  {{- end }}