apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns4

namePrefix: dev-
nameSuffix: -geba

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

patches:
  - path: memory.yaml
    target:
      labelSelector: app=go-template-load
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 10
    target:
      kind: Deployment
      labelSelector: app=go-template-load
  
