apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rollout-exp

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
  - namespace.yaml
  - analysis-job.yaml
  - rollout.yaml
  - service-canary.yaml
  - service-stable.yaml
  - service.yaml
  

configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello from v2!
    - PORT=8080
  options:
    annotations:
      note: api config
    labels:
      type: generated
    disableNameSuffixHash: false

      
