apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myns

namePrefix: dev-
nameSuffix: -geba

commonLabels:
  app: superapi
  version: v1
  env: dev

commonAnnotations:
  description: "This is a the best thing since sliced bread"
  owner: "Geert Baeke"
  created: "2021-11-01"

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  

