apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: demo-secret
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: demosecret
    type: Opaque
    data:
    - objectName: "demosecret"
      key: demosecret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "828a2839-3f66-4169-99a3-d66669029005"
    keyvaultName: "geba18002"
    objects: |
      array:
        - |
          objectName: "demosecret"
          objectType: secret
    tenantId: "484588df-21e4-427c-b2a5-cc39d6a73281"