apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    name: multi-container
spec:
  containers:
  - name: container1
    image: k8s.gcr.io/pause:3.1
  - name: container2
    image: k8s.gcr.io/pause:3.1
  - name: container3
    image: k8s.gcr.io/pause:3.1
