apiVersion: apps/v1
kind: Deployment
metadata:
  name: superapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superapi
  template:
    metadata:
      labels:
        app: superapi
      annotations:
        linkerd.io/inject: "enabled"
    spec:
      containers:
      - name: superapi
        image: ghcr.io/gbaeke/super:1.0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: WELCOME
            value: Welcome from $(IP)
        ports:
        - containerPort: 8080
