apiVersion: v1
kind: Pod
metadata:
  name: wait-init
  labels:
    name: wait-init
spec:
  initContainers:
    - name: wait-container
      image: praqma/network-multitool:latest
      command: ["/bin/bash"]
      args: ["-c","for i in {1..100}; do sleep 1; if host myservice.default.svc.cluster.local; then exit 0; fi; done; exit 1"]
  containers:
  - name: wait-init
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
