apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  
configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello
    - PORT=8080
    
  

      
