kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: superapi
spec:
  podSelector:
    matchLabels:
      app: superapi
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx